### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#100]
## Description
On the first run, it's ok to sync from offline -> online => create offline GUID entities on the server and assign back obtained IDs.
We need also another way round => we need to sync also GUID entities from online to offline. 									                  During the session, other team members could create new tickets and we need to sync them to our project, store it locally.

See FFixThisManager tests `Should test connect routine - valid` and connect once ready

## Sub-tasks
- [x] AddGUIDEntity should not relate on Api - We need to split it
- [x] Assign labelGUIDs for ticket
- [x] Tickets
- [x] Members
- [x] Labels
- [x] Implement `bIsSyncing` in `FSync`
- [x] Update board validation with enhanced labels checking
- [x] Check Full sync procedure
- [x] Check Pull
- [x] Check Push
~~- [ ] Implement all Push overloads~~
- [x] Improve loggin
- [x] Add push, pull commands into window

## Related tickets
- #53 

## Follow up tickets
- N/A

**Comment by alexhajdu** [comment]
![image](https://user-images.githubusercontent.com/1824796/102205575-aad06780-3ecb-11eb-8f02-ececa7912ea1.png)

Connect, push, pull is working. Updating still needs to be done in the separate task: #108
