### ISSUE TITLE
Push sync + uconflict resolving

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#111]
## Description

Implement this procedure
1. create a local ticket -> push
1. update it on the server
1. try to update the same ticket => conflict because the teammate updated the ticket
1. resolve the situation -> pull first, or push to override server information?

Also tests needed to be updated because of rather a quick tempo of introducing the sync features.

## Sub-tasks
- [x] Update only necessary entities
- [x] Check proper sync logging
- [x] Implement local data integrity check
- [x] Create pull with with conflict
- [x] **Need of basic edit entity window**
- [x] Create push with with conflict
- [ ] If conflict and use server data is used - there should be info that all data are pulled, or updated from server, now is `All data is pushed from server`
- [ ] Push / Pull / Sync tickets
- [ ] Push / Pull / Sync labels
- [ ] Push / Pull / Sync members

## Blocking tickets
- N/A

## Related tickets
- N/A

## Follow up tickets
- N/A

**Comment by alexhajdu** [comment]
Sync process
![diff](https://user-images.githubusercontent.com/1824796/106115515-27a06380-6151-11eb-829c-42774e9ac9d1.gif)
