### ISSUE TITLE
Create new generic ticket as an action from the UI

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#124]
## Description
See ticket description...

## Sub-tasks

- [x] Create ticket from toolbar
- [x] Assign default `FT_Generic` for generic ticket
- [x] Possibility to assign due date
- [x]  Possibility to assign labels
- [x]  Possibility to assign members

## Blocking tickets
- N/A

## Follow up tickets

**Comment by alexhajdu** [comment]
Partially done and merged with `e7061b8b77adae765c92e7dbc336672ce6862e32`. Waiting for members to be added

**Comment by alexhajdu** [comment]
Members option has been added.
![image](https://user-images.githubusercontent.com/1824796/110604045-f2435880-8187-11eb-8a46-42a0c838e950.png)
