### ISSUE TITLE
Create new label as an action from the UI

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#134]
## Description
See ticket description...

## Sub-tasks

- [x] Create action for the toolbar
- [x] Create a widget to select the colors from
- [x] Improve selected color visibility (label perhaps)?
- [x] Add label -none-

## Blocking tickets
- N/A

## Related tickets
- N/A

## Follow up tickets
