### ISSUE TITLE
Create filtering widget

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#139]
## Description
The filter criteria will be 

- labels
- members
- due date 
- opened/closed
- text search for title/description
- Logic switch - and, or

## Sub-tasks
- [x] Align correctly in the window
- [x] Create logic operator switch widget ( AND vs OR ) + make filtering logic
- [x] Create Filter by text from title/description widget + make filtering logic
- [x] Update enum values for logic operators
- [x] Filter by date (date picker widget has been already created) - #141 needs to be finished first!
- [x] Update appearance
- [x] Update header tp say Tickets - Filter active - if there are active filters.. Tickets otherwise
- [x] Update logic operator appearance
- [x] Use `FButtonsGroup` if possible and delete unnecessary containers holding widgets as the result of previous impementation
- [x] Use `FButtonsGroup` in the SLabelEditContentWidget::PopulateColors()`  - _still old only one selected at time_ functionality
- [x] Add <kbd>clear</kbd> filter button ticket created

## Blocking tickets

- [x] #141 - It makes sense to finish this one first

## Related tickets
- N/A

## Follow up tickets
- N/A
