### ISSUE TITLE
Update data picker

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#141]
## Description
Data picker needs a new facade and functionality.
![image](https://user-images.githubusercontent.com/1824796/111070083-55a6f080-84d0-11eb-9bc4-1f0d20c974bf.png)

## Sub-tasks

- [x] Update fonts, sizes
- [x] Bring today button in the next row
- [x] Implement additional "checking" functionality for filtering ( this week, this month, next week, overdue )
- [x] Create a widget for the filtering section ( overdue, today, this week, this month)
- [x] Replace buttons with selectable component checkbox ( like logic operations widget )
- [x] Update appearance of buttons
- [x] Implement off to don't filter by date at all. We need to specify because due date none is also a specific and valid type of the due date
- [x] If no selectable is selected, look if the date in the combo is valid. If yes, use that date, else show all tickets
- [x] If - - - and no selectable - show all tickets
- [x] If no valid date and no check box, filter is off, showing all tickets
- [x] Update of combo boxes should clear the selected predefined options ( Today, Tomorrow ... )

**Nice to have**
- [ ] Once - is selected on one of the combo boxes, select - on all of them
- [ ] Once - - - and user choose a value on one of the combo boxes - select today at on the rest of combo boxes

## Blocking tickets
- N/A

## Related tickets
- N/A

## Follow up tickets
- N/A

**Comment by alexhajdu** [comment]
Update with widget in the filter section ![image](https://user-images.githubusercontent.com/1824796/113999142-0c8d5680-985a-11eb-8097-0ec574e87c1e.png)

**Comment by alexhajdu** [comment]
![image](https://user-images.githubusercontent.com/1824796/114301332-96405c80-9ac4-11eb-99a8-c038663cf329.png)
