### ISSUE TITLE
Post It - AActor in the scene

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#146]
## Description
Idea: C++ AActor with the WBP widget

## Sub-tasks

- [x] Ticket not showing data at runtime
- [x] Create a slate layout for the ticket
- [x] Format due date
- [x] Format date and move to the right side
- [x] Remove comma after name (e.g. `alexhajdu,`)
- [x] Resolve texture switching for the exclamation texture for the after due date ticket

⛱️ Weekend

- [x] Delete no more needed `UPostItWidget` and `UPostItWidgetComponent`

## Blocking tickets
- N/A

## Related tickets
- N/A

## Follow up tickets
- N/A
