### ISSUE TITLE
Create high level API in FixThisManager to easily add a GUIDEntity

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#67]
## Description
To add a new guid entity, client code should call `FixThisManager` only. This manager will handle saving the data to disk and sending it to server via user defined API.

## Sub-tasks
- [x] Store locally in the file
- [x] Send to server in case saving to file is successful and the API is present
- [x] Update saved file and newly added entity with the ID obtained in the callback. In case `ID` of the struct is not filled.
- [x] Refactor the code in the `FDataManager`
- [x] Update saved file with the boardURL with the URL obtained in the callback
- [x] Update tests for labels, tickets and members

## Related tickets
- #74
- #76

## Follow up tickets
- N/A 

![FT_hilevel](https://user-images.githubusercontent.com/1824796/92097982-fce7f400-edd8-11ea-8286-e08b9110b84e.png)
