### ISSUE TITLE
Simplify API interface, remove heavy templatization

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#79]
## Description

Simplify, and remove heavy templatization of the API associated code. Use NVI idiom + strategy pattern.

Client code should look like this:

```

struct FSerializableTicket {  /*It's the serialized ticket */ };

FSerializableTicket ticket;
ticket.title = "title";
ticket.desc = "desc";

API* api = new API;
ApiStrategy* trelloStrategy = new ApiStrategyTrello;
api->SetStrategy(trelloStrategy);
api->CreateTicket(ticket);.
```

## Sub-tasks
- [x] Create a new branch for this refactoring
- [x] Resolve config - getCredentials path
- [x] Refactorings
- [x] Resolve all @todos from refactorings
- [x] Update tests 

## Related tickets
- N/A

## Follow up tickets
- #67
