### ISSUE TITLE
Sync - going from offline to online . Going from online to offline.

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#81]
## Description
**Scenario 1** 

It's possible that storage already contains some tickets, labels, etc. If the user wants to go online and use let's say trello, all the tickets need to be recreated on the server and IDs assigned accordingly and storage file saved.

**Scenario 2**

It's possible the user wants to use the trello no longer. We need to remove all the IDs from the Guid entities.

**Scenario 3**

User wants to switch from the trello to Jira. We need to remove all the IDs and replace with the new ones.

## Sub-tasks
- [x] Delete BoardID from FLabelSerial
- [x] Delete BoardID from FListSerial
- [x] Create dummy callback to the API just to be called after the sequence
- [x] Refactor `FDataManager::CreateAndUpdateExistingGUIDEntity`
- [x] Move provision of the GUID entities into the FDataManager
- [x] Make it work for all GUID entities and not only for FLabelSerial
- [x] Going from online to offline mode - meaning to delete the IDs of the GUIDS entities and Board ID

## Related tickets
- N/A

## Follow up tickets
- #74
