### ISSUE TITLE
Sync GUID entities from the config section with the local storage, and if we have API defined, with a server.

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#87]
## Description
Connect the config section to the managers and establish communication. The plugin needs to react to the changes made in the config section.

## Sub-tasks
- [x] ~~Create method to get `FString` from the color in `FLinearColor`~~ *It's not working well*
- [x] Create predefined colors for the Trello API - app - via enum
- [x] Create and save all all labels from the config file 
- [x] Handle credentials from the config file
- [x] Save all default values for the first plugin run
- [x] Create a board with the name provided in the config
- [x] Sync all all labels from the config file  ( online and assign IDs )
- [x] Respond to the change made in the config file - create a new label - - save in the file and if Api, on the server too
- [x] Respond to the change made in the config file - color change - save in the file and if Api, on the server too
- [x] ~~Create customization~~
![image](https://user-images.githubusercontent.com/1824796/98469422-ba2f0780-21df-11eb-80a4-06934e701f31.png)

## Blocking tickets
- N/A

## Related tickets
- N/A

## Follow up tickets
- N/A
