### ISSUE TITLE
Trello config window

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#96]
## Description
Trello config window to enter key, secret.

## Sub-tasks
- [x] Make window instead of tab
- [x] Create Close/Ok widget for closing modal windows
- [x] Show error area
- [x] Windows header 
- [x] Styled buttons
- [x] Info area
- [x] Add board name and the decision widget for creating new or connecting to the existing board

## Blocking tickets
- N/A

## Related tickets
- N/A

## Follow up tickets
- N/A

**Comment by alexhajdu** [comment]
Some of the subtasks will be reusable on the other windows - e.g. Ok/Close buttons...

**Comment by alexhajdu** [comment]
Quick preview
![image](https://user-images.githubusercontent.com/1824796/99261064-7f028900-281c-11eb-98ee-e4c2a5c65fa9.png)
