### ISSUE TITLE
Connect button and it's functionality

### ISSUE THREAD

**Issue by alexhajdu** [alexhajdu/FixThis_Project-management-plugin-for-UE4#98]
## Description
Create a connect button in the toolbar in the main window. 
> See the internal wiki for reference.

## Sub-tasks
- [x] Add to toolbar
- [ ] ~Enable only if Trello or Jira is set up~

Set-up connect procedure

- [x] Get info about board -if not exist - create one

## Blocking tickets
- #100 

## Related tickets
- N/A

## Follow up tickets
- N/A
